[package]
edition = "2021"
name = "AArch64_ReportException"
version = "0.0.0"

[dependencies]
log = "0.4.21"

[dependencies.AArch64_ExceptionClass]
path = "../AArch64_ExceptionClass"

[dependencies.Bit]
path = "../Bit"

[dependencies.CurrentSecurityState]
path = "../CurrentSecurityState"

[dependencies.ESR_set]
path = "../ESR_set"

[dependencies.FAR_set]
path = "../FAR_set"

[dependencies.HavePFAR]
path = "../HavePFAR"

[dependencies.HaveRME]
path = "../HaveRME"

[dependencies.IsSecureEL2Enabled]
path = "../IsSecureEL2Enabled"

[dependencies.Mk_ESRType]
path = "../Mk_ESRType"

[dependencies.PFAR_set]
path = "../PFAR_set"

[dependencies.Zeros]
path = "../Zeros"

[dependencies.common]
path = "../common"

[dependencies.integer_subrange]
path = "../integer_subrange"

[dependencies.set_subrange_zeros]
path = "../set_subrange_zeros"

[dependencies.u__UNKNOWN_bits]
path = "../u__UNKNOWN_bits"
